In [38]:
import pandas as pd

data_csv = "gpr.csv"

data_df = pd.read_csv(data_csv)


data_df.head()

,DATE,DAY_NUMBERS,N11D,GPRD_RAW,GPRD_THREAT_RAW,GPRD_ACT_RAW,GPRD_SHARE,GPRD_THREAT_SHARE,GPRD_ACT_SHARE,GPRD*,GPRD_THREAT,GPRD_ACT,EVENT,*value of the index on the day the newspaper was published
0,19850101,1985.000000,822,6,4,2,0.73%,0.49%,0.24%,142,113,266,NaN,"For instance, GPR_DAILY spikes on September 12..."
1,19850102,1985.002738,891,3,2,1,0.34%,0.22%,0.11%,65,52,123,NaN,NaN
2,19850103,1985.005476,1300,3,3,0,0.23%,0.23%,0.00%,45,53,0,NaN,NaN
3,19850104,1985.008214,1287,9,6,3,0.70%,0.47%,0.23%,136,108,255,NaN,NaN
4,19850105,1985.010951,897,3,2,1,0.33%,0.22%,0.11%,65,52,122,NaN,NaN

In [39]:
gprdaily_df = data_df[['DATE','GPRD*']]

gprdaily_df.head()

       DATE  GPRD*
0  19850101    142
1  19850102     65
2  19850103     45
3  19850104    136
4  19850105     65

In [34]:
gprdaily_df = gprdaily_df.iloc[9131:,]

gprdaily_df = gprdaily_df.rename(columns = {"GPRD*" : "GPRD"})

gprdaily_df = gprdaily_df.rename(columns = {"DATE" : "Date"})

#gprdaily_df['Date'] = pd.to_datetime(gprdaily_df['Date'])

gprdaily_df.head()

NameError: name 'gpr2_df' is not defined

In [29]:
gprdaily_df.to_csv("gpr_clean.csv", index=False, encoding='utf8')